### ISSUE TITLE
[🐛 Bug]: V9 Mock Spys not Returning Request Body

### ISSUE THREAD

**Issue by VelascoTM** [webdriverio/webdriverio#13765]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

Standalone Mode

### What happened?

Unable to get the request body like I did in V8 using this example found here. https://webdriver.io/docs/mocksandspies/#spies 

### What is your expected behavior?

Being able to get the request info from the spy, specifically the body.

### How to reproduce the bug.

Follow the example - https://webdriver.io/docs/mocksandspies/#spies

### Relevant log output

```typescript
NA
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
We have switched our mock implementation to use WebDriver Bidi which doesn't yet support returning the body payload. We will add support for it as soon as it gets shipped in the browser.

**Comment by tmeisner7** [comment]
@christian-bromann I was wondering if you would know when this issue might be fixed in Bidi and WebDriver, since there is a big blocker for us. Thanks.

**Comment by christian-bromann** [comment]
@tmeisner7 last time I check the protocol didn't provide the response body but it is planned to add it. I haven't recently checked what is the status of it.

**Comment by Badisi** [comment]
I had the same blocker and since I couldn't wait for browsers to implement it, I had it working with **Puppeteer**.

Basically, I added a new `getPage()` command in `wdio` that exposes the Puppeteer's apis that would allow me to spy on requests.

@christian-bromann, I don't know if that could be of any use, implemented or documented somewhere ? (until Bidi is fully supported).

#### install puppeteer
```
npm install --save-dev puppeteer-core
```

#### polyfills/puppeteer.ts
```ts
import { browser } from '@wdio/globals';
import type { Page } from 'puppeteer-core';

declare global {
    namespace WebdriverIO {
        interface Browser {
            getPage: () => Promise<Page>;
        }
    }
}

browser.addCommand('getPage', async (): Promise<Page> => {
    if (!('page' in browser.__propertiesObject__)) {
        const puppeteerBrowser = await browser.getPuppeteer();
        const pages = await puppeteerBrowser.pages();
        const controlledPageUrl = await browser.getUrl();
        const page = pages.find(p => p.url() === controlledPageUrl);
        if (!page) {
            throw new Error('Error: not able to find the current page using Puppeteer');
        }
        browser.__propertiesObject__['page'] = { value: page };
    }
    return browser.__propertiesObject__['page'].value;
});
```

#### specs/test.e2e.ts
```ts
import './polyfills/puppeteer';
import type { Page } from 'puppeteer-core';

describe('my tests', () => {
  let currentPage: Page;

  beforeAll(async () => {
    currentPage = await browser.getPage();
  }

  it('test1', async () => {
    const [response] = await Promise.all([
      currentPage.waitForNavigation(),
      browser.url('my-url')
    ]);
  }

  it('test2', async () => {
    const [response] = await Promise.all([
      currentPage.waitForResponse(resp => resp.url().includes('/token')),
      browser.url('my-url')
    ]);
    await expect(response.request().method()).toEqual('POST');
    await expect(response.status()).toEqual(200);

    const requestBody = response.request().postData();
    await expect(requestBody).toContain('code=');
    
    const responseBody = await response.json() as Record<string, unknown>;
    await expect(responseBody).toEqual(jasmine.objectContaining({
      'id_token': jasmine.any(String)
    });
  }
}
```

**Comment by christian-bromann** [comment]
> I don't know if that could be of any use, implemented or documented somewhere ? (until Bidi is fully supported).

Very interesting! It makes sense to add this to our mock docs, would you be open to raise a PR?

**Comment by tmeisner7** [comment]
@Badisi thanks for workaround. 
@christian-bromann, should we use this approach instead of Mocks or should we wait the fix?
currently our project has many Mocks objects and it will be hard to replace them all.

**Comment by christian-bromann** [comment]
> should we use this approach instead of Mocks or should we wait the fix?

I think this would introduce a lot of tech debt when we are almost there to have support for it on the protocol level.

**Comment by Badisi** [comment]
Guys, I have updated my polyfill so that we could stay closer to what wdio was doing.

For instance, this allow us to do something like:
```ts
const mock = await browser.mockRequest('http://localhost:4200/api', { method: 'get' });
await browser.url('my-url');
await expect(mock.calls[0].body).toEqual({ success: true })
```

Only difference would be to use **.mockRequest()** instead of **.mock()** (which is quite acceptable I guess).

I took example on the [spies doc](https://webdriver.io/docs/mocksandspies#spies), which is quite simple, but I guess more work would need to be done for other use cases (like support for wildcards urls, and maybe attach the response/request to the call object too). It's actually hard for me to tell what is still supported and what is broken.

@christian-bromann, what do you think about this approach ? and do you think it would be worth it to spend more time on it and maybe make it a custom wdio service ? (at least until wdio support it on its own). Also, why the old implementation was not kept where BiDi was not ready ? (this is clearly a huge breaking.. 😕).

@tmeisner7, if I provide such a package, would you be willing to participate and add support for more use cases ?

**Comment by christian-bromann** [comment]
> and do you think it would be worth it to spend more time on it and maybe make it a custom wdio service ?

I think this would be the best way forward.

> this is clearly a huge breaking.. 😕

You may thing this is obvious but it isn't. The majority of WebdriverIO functionality depends on software we have no control over. What may be a breaking change for some user isn't for others.

> Also, why the old implementation was not kept where BiDi was not ready ?

We don't have the capacity to maintain legacy code. I think really strategic about what code I like to maintain and which I throw away. I was very much aware that migrating to Bidi will likely break things. This is because of two reason: 1) there are so many use cases how you can use this feature and how it actually impacts the browser 2) it is not 100% clear how people use this in the first place. Due to the fact that the project has limited resources my approach for maintenance is rather radical than conventional/conservative. I am leaning towards risking potential breaking changes because it allows me to receive feedback from users like you. If I would keep legacy code around it usually results in users never giving feedback at all, which results in having to maintain code forever, which you can't do with a small team. This is why we did this change as part of v9 which essentially justifies this change after all.

**Comment by Badisi** [comment]
@christian-bromann, thanks for the clarification.
Completely understand the reasoning but wished it was clearer in the changelog or documentation that mocks were broken and which use cases were broken in particular. Would have saved a lot of time and headache.

----

Anyway, after more digging here are my conclusions 😊:
- BiDi implementation seems to only miss returning body responses in requests
   https://github.com/w3c/webdriver-bidi/issues/747

   So for those only interested in testing request's responses, I've updated my code above, which now allows:
   ```ts
   const mock = await browser.mock('http://localhost:4200/api', { method: 'get' });
   const [response] = await Promise.all([
      mock.waitForResponse(),
      browser.url('http://localhost:4200')
   ]);
   ```

   My thoughts were that when you want to test the response of a request, you must necessarily wait to receive that response before being able to do so. This implies always using `mock.waitForResponse`. Based on this principle, I found it more elegant to return the `response` directly with `waitForResponse` rather than using `mock.calls[0].response` later on. Therefore, I overrode `waitForResponse` to use **Puppeteer** directly behind the scenes. This approach is minimally intrusive, and once the feature is added to BiDi, the update should also be less cumbersome (i.e. only the signature of `response` would change).

   After all, I don't think making it a custom service is a good idea as there are some edge cases where it doesn't work as expected (ex: when using `waitForReponse` along with other mock original apis like `respond` - Puppeteer and BiDi cannot listen altogether to requests, so inevitably one catches the request first and leaves the other one timed out).

   => So I might just provide a PR to update the documentation with more temporary info and a link to a Gist with the polyfill.

- Current WebdriverIO BiDi mock's implementation could be improved:
   - currently listeners ('continue', 'fail', 'match', 'overwrite', 'request') are only notifications, you cannot interact with them. Would be nice being able to decide if the request should be aborted, continued..., there.

- WebdriverIO's documentation could be improved:
   - part of the documentation still refers to mock examples that are broken
   - also I found out that pattern using `**` (ex: `browser.mock('**/foo/)`) are discouraged because it can froze everything
       - https://github.com/kenchris/urlpattern-polyfill/issues/121
       - So doc can be improved in few places to avoid people getting stuck without knowing why and also explaining that `URLPattern` is used under the hood so that they can test it themselves.

   => I might provide a PR for that when I have time

**Comment by tmeisner7** [comment]
@christian-bromann 
I still don't get a response body from Bidi. And according to this ticket: https://github.com/w3c/webdriver-bidi/issues/747, it has not fixed.
Do you know about any plans to fix this request? It is a big blocker for our project to migrate to v9

**Comment by christian-bromann** [comment]
> Do you know about any plans to fix this request?

Afaik this will eventually land in the browser at which point we can support it in WebdriverIO.

**Comment by Badisi** [comment]
Seems like BiDi has finally implemented returning body responses in requests:
- https://github.com/w3c/webdriver-bidi/issues/747

@christian-bromann any plan for this ?

**Comment by christian-bromann** [comment]
That's great news, any contributions are welcome!

**Comment by dprevost-LMI** [comment]
To clarify, we are interested only in the response's body only. The request body mentioned in the title is just misleading, right?

**Comment by dprevost-LMI** [comment]
FYI:
- `call.body` is now back
- `call.postData` (as [documented here](https://webdriver.io/docs/api/browser/mock/#parameters)) is still missing...

**Comment by Badisi** [comment]
@dprevost-LMI, thanks a lot for adding `call.body` !

I can confirm that it works, but I ran into an issue when using `mock.waitForResponse()`.

In fact `waitForResponse()` only waits until `mock.calls` contains an entry.
However, the body property is attached asynchronously afterward.
As a result, `mock.waitForResponse()` may resolve before the response body is actually available, which makes it unreliable for tests that need to inspect the response payload.

In the example below, I'm waiting for a GET request to complete so I can assert on the response data.
When `waitForResponse()` resolves, `mock.calls[0].body` is still undefined.
A few seconds later, the body is populated as expected.

```ts
await browser.url('about:blank');
const mock = await browser.mock('https://dev-fijd1e9x.us.auth0.com/.well-known/openid-configuration');
await browser.url('https://badisi.github.io/auth-js/demo-app/auth-js/');
await mock.waitForResponse();
console.log(mock.calls[0].body); // => returns undefined
setTimeout(() => {
    console.log(mock.calls[0].body); // => returns the actual request body
}, 5000);
```

**Comment by dprevost-LMI** [comment]
Make sense, someone actually workaround it like [here](https://github.com/webdriverio/webdriverio/pull/15192/changes#diff-86320f7ad604f51f053222639795060b3c9a44eb70ba9abeffd20279c0ba2e37R114-R117) with the below:
```ts
        await browser.waitUntil(() => mock.calls[0]?.body !== undefined, {
            timeoutMsg: 'Expected response body to be populated',
            timeout: 5000
        })
```

Do you mind entering an issue, I'll look into it!

**Comment by Badisi** [comment]
@dprevost-LMI, please find the corresponding issue here: https://github.com/webdriverio/webdriverio/issues/15295

And thanks already for the fix and the quick response !
