### ISSUE TITLE
[🐛 Bug]: Unable to get browser from selenium grid post upgrading from V8 to V9

### ISSUE THREAD

**Issue by Bjb20** [webdriverio/webdriverio#14946]
### Have you read the Contributing Guidelines on issues?

- [x] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

9.21.0

### Node.js Version

24.7

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript

```

### What happened?

I am getting below provided error after i have upgraded my webdriver io version from V8 to V9 (9.21.0). While requesting browser from selenium grid (4.38.0) i am getting below provided error, I tried tweaking the capabilities in multiple ways but its still not resolved. So could you please check this. 

Error:-  webDriverError: overlapping keys between w3c always and first match capabilities: [requester:project-id, requester:project-branch-id]  when running "https://selenium-hub:4444/selenium/session" with method post and args 

But at the same time test is still working in same selenium grid with V8 version of webdriver io

### How to reproduce the bug.

created a webdriver io test automation framework with latest version 9.21.0 and tried to run test in selenium grid. 

### Relevant log output

```typescript
Error:-  @wdio/runner webDriverError: overlapping keys between w3c always and first match capabilities: [requester:project-id, requester:project-branch-id]  when running "https://selenium-hub:4444/selenium/session" with method post and args {capabilities}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

**Comment by mccmrunal** [comment]
@Bjb20 Could you share your exact capability configuration?

**Comment by Bjb20** [comment]
I tried with multiple capabilities please find below

1. 

capabilities: [{
browserName: 'chrome',

acceptInsecureCerts: true,

 }],

2. 
capabilities: [{

maxInstances: 10,

//platformName: 'windows',

browserName: 'chrome',

//browserName: 'Microsoft Edge',

//browserName: 'firefox',

//browserVersion: '127.0',

acceptInsecureCerts: true,

//

"goog: chromeOptions": {

//

args: ['headless', 'disable-gpu']

//

},

'wdio: enforceWebDriverClassic': true

// }

]

3.

capabilities: [{

browserName: 'chrome',

'goog:chromeOptions': {

},

args: [

1,

'--headless',

--disable-gpu',

'--no-sandbox',

'--disable-dev-shm-usage',

'--disable-web-security',

'--window-size=1920, 1080',

prefs: {

},

'profile.default_content_setting_values.notifications': 2,

'profile.default_content_settings.popups': 0,

'profile.managed_default_content_settings.images': 2

excludeSwitches: ['enable-automation'],

useAutomation Extension: false

acceptInsecureCerts: true,

'wdio:maxInstances': 10,

'wdio: enforceWebDriverClassic': true

}],

And tried many more here i just put these as eg

**Comment by Bjb20** [comment]
Thanks @mccmrunal for quick support. Any ETA when the MR will be approved & the issue will be fixed??

**Comment by Bjb20** [comment]
When this issue will be fixed ??

**Comment by mccmrunal** [comment]
The fix is already posted , it will be reviewed and merged soon hopefully!

**Comment by Bjb20** [comment]
Yes, Waiting for last 2 weeks to get the fix merged.

**Comment by Bjb20** [comment]
Post this fix , i have upgraded to to version 9.23.2 but still getting the same error 

01:00:06 [0-4] 2026-01-18T19:30:06.684Z DEBUG webdriver: request failed due to response error: unknown error

01:00:06 [0-4] 2026-01-18T19:30:06.686Z INFO webdriver:

Retrying 1/3

01:00:06 [0-4] 2026-01-18T19:30:06.686Z INFO webdriver: [POST] https://selenium-hub: 4444/selenium/session

01:00:06 [0-4] 2026-01-18T19:30:06.686Z WARN webdriver: WebDriverError: Overlapping keys between w3c always and first match capabilities: [requester: project-id, requester: project-branch-id] when running "https://selenium-hub: 4444/selenium/session"

with method "post”

**Comment by mccmrunal** [comment]
Please drop your latest config here , I will try to check it at my earliest

**Comment by Bjb20** [comment]
Below is my complete config file

import (generate } from multiple-cucumber-html-reporter';
import { browser } from '@wdio/globals';
export const config = (
automationProtocol: 'webdriver',
hostname: "//selenium-hub",
protocol: "https",
path: "/selenium",
excludeDriverLogs: ['*'],
tsConfigPath: './tsconfig.json',
specs:
`${process.cwd())/test/features/*.feature",
1
exclude: [],
maxInstances: 10,
capabilities: [{
browserName: 'chrome',
acceptInsecureCerts: true,
"goog:chromeOptions": {
args: ['disable-gpu'],
'wdio: enforceWebDriverClassic': true
},
}],
logLevel: 'debug',
bail: 0,
waitforTimeout: 10080,
connectionRetryTimeout: 450000,
connectionRetryCount: 3,
services: [],
framework: 'cucumber',
reporters: ['spec',
['cucumberjs-json', {
jsonFolder: 'results/json/',
language: 'en',
},
],
]
cucumberOpts: (
require: ("./test/step-definitions/*.ts"],
requireModule: ['ts-node/asm'],
backtrace: false,
dryRun: false,
failfast: false,
snippets: true,
source: true,
},
strict: false,
tags: @Test',
timeout: 380000,
ignoreUndefined Definitions: false
},
beforeFeature: asyne function (uri, feature) (
try {
await browser.setWindowSize(1980, 1080); await browser.url("www.google.com");
catch (strErrMsg) (
throw Error('Before feature method not completed $(strErrMsg)");
anComplete: function (exitCode) (
generate((
jsonDir: 'results/json/", reportPath: 'results/html/‘
});
console.log(exitCode);
process.exit(0);
}
}

**Comment by mccmrunal** [comment]
@Bjb20 
I see many issues with the config

args: ['disable-gpu'] was at the root of capabilities. It must be inside goog:chromeOptions.
automation Protocol -> should be automationProtocol

please review once the config file if error persists I will try to resolve

**Comment by Bjb20** [comment]
@mccmrunal  The error u r seeing in the config file because , it was scanned and pasted. in actual it automationProtocol only and args: [] inside goog:chromeOptions only, so please ignore these. there is no error in the config file.  Also i have updated the config in the comment.

**Comment by mccmrunal** [comment]
Just to be on the same page can you create a small repo and paste the link here

**Comment by Bjb20** [comment]
@mccmrunal Created a repo with the required details , please find below https://github.com/Bjb20/WebdriverIoVersion9

**Comment by mccmrunal** [comment]
@Bjb20  I replicated the repo and there are multiple issues in wdio.conf file also there are no test cases to run , please check and give steps to replicate also

**Comment by Bjb20** [comment]
@mccmrunal , I have updated the repo, there should not be any error, Please check the latest one , Also no test case is needed though, just need to hit the grid and get the browser and navigate to "www.google.com" which is happening in before feature hook. still i have added a simple test, grid version is 4.39.0. Please let me know if u still see any error

**Comment by mccmrunal** [comment]
@Bjb20 there were still errors I fixed those thats fine

Instead of connecting to selenium hub I connected to docker selenium docker locally and I feel that the error is resolved in current release .

Please do fresh npm install and try to run again!

<img width="1752" height="594" alt="Image" src="https://github.com/user-attachments/assets/d981f425-4007-49fb-a405-b0377d2e069c" />

**Comment by Bjb20** [comment]
@mccmrunal  In local system its working fine (with V9). While requesting browser from selenium hub only facing this issue. Also as i mentioned earlier it was working in V8 & still works. getting this error post V9 only. Also i see some changes u have made in the fix https://github.com/mccmrunal/webdriverio/commit/54b9c92a10db4b17e884a9a6521db2bb6ad9a9d5, So can you see if any change needed to get this issue resolved??
