### ISSUE TITLE
"unknown error: call function result missing 'value'"

### ISSUE THREAD

**Issue by probablyup** [webdriverio/webdriverio#2631]
## The problem

At my work, we use webdriverio with chrome. It appears that the chromedriver may be sending responses back that webdriverio can't handle.

## Environment

* WebdriverIO version: 4.11.0 
* Node.js version: 8.9.4
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): standalone
* chrome 65.0.3325.146-1

## Details

Certain commands sent to Chrome reap responses that webdriverio doesn't seem able to handle.

## Link to Selenium/WebdriverIO logs

```
[chrome #0-0] Failed: unknown error: call function result missing 'value'
[chrome #0-0] Error: An unknown server-side error occurred while processing the command.
[chrome #0-0]     at elementIdValue("0.9833432935579824-2", "foo") - setValue.js:46:80
```

```
[chrome #0-0] Failed: unknown error: call function result missing 'value'
[chrome #0-0] Error: An unknown server-side error occurred while processing the command.
[chrome #0-0]     at execute(<Function>, 92, 2219) - scroll.js:104:26
```

I can confirm that downgrading to chrome 64.0.3282.186-1 fixes it.

**Comment by christian-bromann** [comment]
Can you provide Chromedriver logs?

**Comment by probablyup** [comment]
Hmm, how would I go about doing that? They don’t output anywhere I can see
by default.

**Comment by flyHe** [comment]
same issue with chrome 65
`
unknown error: call function result missing 'value'
running chrome
Error: An unknown server-side error occurred while processing the command.
`
`at elementIdValue("0.22831194167614743-1", "xxx@mailinator.com") - setValue.js:46:80`

**Comment by christian-bromann** [comment]
Yes, please update the Chromedriver then. Doesn't seem to be an issue with WebdriverIO.

**Comment by JulsRicketti** [comment]
Having the same issue.
I just updated ChromeDriver (now at 2.36.540469) and Chrome (now at 65.0.3325.146), but I am still getting this issue. Have I missed something?

**Comment by joshden** [comment]
I just started having this problem on Windows after updating from Chrome Version 63.0.3239.132 (Official Build) (64-bit) to 65.0.3325.146 (Official Build) (64-bit).

But after updating chromedriver from 2.33 to 2.36, I am no longer seeing this error.

**Comment by hitex** [comment]
I updated Google Chrome to 65.0.3325.146 and ChromeDriver to 2.36.540471 and am still getting this issue.

**Comment by MattiSG** [comment]
For all those who still get the error: are you sure you have updated the actually used dependency to `chromedriver`? 🙂

If you manage `chromedriver` yourself, i.e. you execute `chromedriver` in some Terminal tab before launching your tests, then you should indeed update the executable itself.
If, on the other hand, you are executing `chromedriver` through `wdio-selenium-standalone-service`, you'll need to update it to `v0.0.10` to get [the update](https://github.com/webdriverio/wdio-selenium-standalone-service/pull/41).

**Comment by KumarSunil20** [comment]
Thanks @BorisOsipov,
I have updated below mentioned dependencies and issues is now resolved.

wdio-selenium-standalone-service  -v=0.0.10
selenium-standalone -v=6.13.0
chromedriver -v=2.36.0

**Comment by BorisOsipov** [comment]
@KumarSunil20 see comment https://github.com/webdriverio/webdriverio/issues/2631#issuecomment-372875052

**Comment by Ivor** [comment]
I needed to `brew services restart chromedriver` after running `brew upgrade chromedriver` and then it worked fine. Thank you!

**Comment by dislev** [comment]
So if anyone using a Mac and using Homebrew what I did was...
1. brew upgrade `brew upgrade selenium-server-standalone`
2. brew upgrade `brew upgrade chromedriver`

These are my versions now for what is working form me...
Chrome - `Version 65.0.3325.162 (Official Build) (64-bit)`
Selenium - `Selenium server version: 3.11.0, revision: e59cfb3` (via `selenium-server --version`)
Chromdriver - see screenshot...

<img width="612" alt="screen shot 2018-03-15 at 11 27 19 am" src="https://user-images.githubusercontent.com/6194273/37483849-1a6a6c40-2844-11e8-9953-4e19080561f2.png">

**Comment by dheerajbhaskar** [comment]
Kudos to @christian-bromann and the wdio community for the speed of fixes. The other communities/projects are yet to figure out the issue let alone release a fix. 

I'm happy to be a webdriverio user, much love to you all.

**Comment by KumarSunil20** [comment]
I am facing an issue with latest chrome browser v65.
I am getting this error message more often "Promise was rejected with the following reason: java.net.ConnectException: Connection refused: connect". Didn't get any solution to resolve this. I have updated all dependencies to the latest one.

Dependencies:
"dependencies": {
    "allure-commandline": "^2.5.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-register": "^6.26.0",
    "chai": "^4.1.2",
    "chromedriver": "^2.36.0",
    "copy-dir": "^0.3.0",
    "hh-mm-ss": "^1.2.0",
    "lodash": "^4.17.5",
    "selenium-standalone": "^6.13.0",
    "wdio": "^1.0.3",
    "wdio-allure-reporter": "^0.1.2",
    "wdio-chromedriver-service": "^0.1.2",
    "wdio-cucumber-framework": "^1.1.0",
    "wdio-phantomjs-service": "^0.2.2",
    "wdio-selenium-standalone-service": "^0.0.10",
    "wdio-spec-reporter": "^0.1.4",
    "webdriverio": "^4.12.0",
    "xlsx": "^0.11.6"
  },
  "devDependencies": {
    "babel-jest": "^23.0.0-alpha.0",
    "babel-polyfill": "^6.26.0",
    "eslint": "^4.19.0",
    "eslint-config-airbnb-base": "^12.1.0",
    "eslint-plugin-import": "^2.9.0",
    "forever": "^0.15.3",
    "http-server": "^0.11.1",
    "jest": "~21.2.0",
    "wdio-firefox-profile-service": "^0.1.1"
  }

Wdio.conf:
services: ['firefox-profile', 'selenium-standalone'],
capabilities: [{
        // maxInstances can get overwritten per capability. So if you have an
        // in-house Selenium grid with only 5 firefox instance available you can
        // make sure that not more than 5 instance gets started at a time.
    //     maxInstances: 1,
        browserName: 'firefox',
    }, {
        browserName: 'chrome',
        chromeOptions: {
            args: ["start-maximized"],
            prefs: {
                'download.default_directory': __dirname + '\\downloadedFiles',
                'profile.default_content_settings.popups': 0
            },
        },
    } 

Let me know if any one has idea to resolve this issue.

**Comment by ckurban** [comment]
I had the similar issue and despite that I have upgraded to `chromedriver 2.36` selenium standalone  was still picking up old version `2.33.5` of the chromedriver.

Solution worked for me is : 

1. I had to delete repo and clone it
2. npm install 
3. npm i selenium-standalone -g // install selenium standalone globally
4. selenium-standalone install // very important step otherwise selenium will still try to point to the old version of the chromedriver.

I hope this helps

**Comment by KumarSunil20** [comment]
@ckurban Can you mention what is the repository that I need to delete.

**Comment by serbanghita** [comment]
In your `package.json` upgrade to the latest minor versions:

*New* - working

```
    "selenium-standalone": "^6.13.0", <---- this bumps the chromedriver version
    "webdriverio": "^4.12.0",
```

*Old* - not working

```
    "selenium-standalone": "^6.12.0",
    "webdriverio": "^4.10.2",
```

Do again:

1. `npm install`
1. `./node_modules/.bin/selenium_standalone install` then `start`

**Comment by andrea-raabe** [comment]
I have upgrade the latest version: selenium-standalone@6.13.0 and webdriverio@4.12.0  but it still does not work.

Selenium/WebdriverIO logs:

`unknown error: call function result missing 'value'
An unknown server-side error occurred while processing the command.`

**Comment by LaiaPR** [comment]
Updating my package.json to newest versions:

```
"wdio-selenium-standalone-service": "~0.0.10",
"webdriverio": "~4.12.0"
```

Solved the issue for me. Thanks!!

**Comment by Ravikanthbmc** [comment]
Just try updating the webdriver manager, it picks up the latest available chrome driver.
webdriver-manager update
webdriver-manager start

This resolved my issue.

**Comment by Mosho1** [comment]
Had the issue with 2.33, specified 2.36 in both `selenium.install` and `selenium.start` and now it works.

**Comment by AlexCharlton93** [comment]
Thanks, this also fixed the issue for us:

"selenium-standalone": "^6.13.0"
"webdriverio": "^4.12.0"

**Comment by fniewijk** [comment]
We have selenium-standalone installed globally and not attached to the project. For us running `selenium-standalone install --drivers.chrome.version=2.36 --drivers.chrome.baseURL=https://chromedriver.storage.googleapis.com
` fixed the problem.

**Comment by MarcinGren** [comment]
Updating Chromedriver worked.

After update:
Chrome version: Version 66.0.3359.139 (Official Build) (64-bit)
ChromeDriver version: ChromeDriver 2.38.552522

**Comment by NDuggan** [comment]
If you're using brew Homebrew and are having trouble updating `chromedriver` you might need to uninstall it and reinstall it again as it has been migrated to a cask.

```
Error: No available formula with the name "chromedriver"
It was migrated from homebrew/core to caskroom/cask.
You can access it again by running:
  brew tap caskroom/cask
And then you can install it by running:
  brew cask install chromedriver
```

**Comment by wenyenwei** [comment]
After downloading the latest v2.38 chromedriver, update selenium-standalone and webdriverio, it still doesn't work. 
I installed npm chromedriver and it solved everything :)

**Comment by sarla2010** [comment]
Updating chrome driver fixed the issue to latest stable 2.38.
Thanks.

**Comment by dtandersen** [comment]
Upgraded from 2.28.455520 to 2.38.552522 and it worked.

**Comment by sumeetp4** [comment]
Hey @BorisOsipov , if I'm using Appium and running tests on mobile browser chrome (version 66), do I need to update the chrome driver service?

**Comment by yashwp** [comment]
I'm facing the same problem.
```
  - Failed: unknown error: call function result missing 'value'
  (Session info: chrome=71.0.3578.98)
  (Driver info: chromedriver=2.24.417431 (9aea000394714d2fbb20850021f6204f2256b9cf),platform=Windows NT 10.0.17134 x86_64)

```

I've tried installing the chromedriver `v2.45` but it is not working

**Comment by abjerstedt** [comment]
@yashwp this is a closed issue. We may or may not see this to respond to. Questions like the one would be better asked in our gitter channel.

As for your actual question, i'm not going to debug a chromedriver binary that doesn't support anything beyond like Chrome 55.

**Comment by yashwp** [comment]
@abjerstedt I've asked also asked on your Gitter channel, but apparently, nobody cared to reply and its already been 3 -4 days!!! 
Just in case if you know how to fix the issue, please respond to this SO question 
https://stackoverflow.com/questions/54230191/chrome-version-71-x-unknown-error-call-function-result-missing-value

**Comment by ildarius** [comment]
Updated to the following chromedriver on ubuntu and it fixed the error
https://chromedriver.storage.googleapis.com/2.46/chromedriver_linux64.zip

Was getting:
PHP Fatal error:  Uncaught Facebook\WebDriver\Exception\UnknownServerException: unknown error: call function result missing 'value'
(WARNING: The server did not provide any stacktrace information)

**Comment by pioz** [comment]
If you are using the gem `chromedriver-helper` run the command `chromedriver-update` solve the problem for me.

**Comment by atefBB** [comment]
Updating to `chromedriver` version `2.46` fix the issue for me !
