### ISSUE TITLE
isExisting & isVisible returns incorrect value for element that exists more than once

### ISSUE THREAD

**Issue by cuongluu8** [webdriverio/webdriverio#2800]
## The problem

Consider the following markup
```html
<html>
    <body>
        <ul class="list">
            <li class="list-item">
                <div>
                    <p>One</p>
                </div>
            </li>
            <li class="list-item">
                <div>
                    <p>Two</p>
                    <div class="error"><p>error</p></div>
                </div>
            </li>
        </ul>
    </body>
</html>
```
Notice the `.error` element only exists on the 2nd `.list-item`
Now, using the REPL tool, and running the following command
`browser.$$('.list-item')[0].element('.error').isExisting()` returns `true`, where it should return `false`

## Environment

* WebdriverIO version: `4.10.2`
* Node.js version: `6.12.3` - also tried with `8.9.4`
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): REPL for above example, but using wdio testrunner in my real enviroment with real test
* if wdio testrunner, running synchronous or asynchronous tests: `synchronous`
* Additional wdio packages used (if applicable): `"wdio-browserstack-service": "^0.1.14", "wdio-chromedriver-service": "^0.1.2", "wdio-cucumber-framework": "^1.1.0"`

## Details

If the `.error` element is also removed from the 2nd `.list-item`, then the correct value is return for `isExisting()`.  Seem the `isExisting` and `isVisible` is being applied globally rather than within the context of the element it's being called on.

## Code To Reproduce Issue [ Good To Have ]
see The Problem above

**Comment by cuongluu8** [comment]
I've been investigating workaround for this.  It looks like `getHTML()` command seems to work as expected.  e.g. `browser.$$('.list-item')[0].element('.error').getHTML()` will throw an exception because the `.error` element does not exist.  Therefore one workaround is to create a new command as such
```js
browser.addCommand('isExistingFixed', function () {
  try {
    this.getHTML();

    return true;
  } catch (error) {
    return false;
  }
});
```

Will go with this for now, would be nice to know if this is indeed a bug or whether I'm missing something.

**Comment by erwinheitzman** [comment]
Have you checked what browser.$$('.list-item')[1].element('.error').isExisting() returns?
I'm not 100% sure but I believe the DOM is traversed from bottom to top.
Can you let me know the result? 🙂

**Comment by cuongluu8** [comment]
@erwinheitzman it returns `true` as well.
However, `browser.$$('.list-item')[0].element('.error').getHTML()` throws exception as the `.error` element does not exists.
Whereas `browser.$$('.list-item')[1].element('.error').getHTML()` will return the `.error` markup.
This means that the DOM is not traversed from bottom to top.

So `getHTML()` seems to work properly, whereas `isExisting` & `isVisible` does not

**Comment by erwinheitzman** [comment]
Thank you for checking, I think it is as you say then. There's already a issue open regarding the scope / chaining of elements and this will be fixed in v5 of webdriverio so I ain't sure if we should keep this issue open or not. I will leave it for now and I will do a check later to confirm the issue.

**Comment by christian-bromann** [comment]
@cuongluu8 thanks for filing the issue. We fixed this in v5 and I don't think we can fix this easily in v4 given that we will deprecate it. Therefor I am closing this.

**Comment by cuongluu8** [comment]
OK fair enough - my workaround should suffice.
"There's already a issue open regarding the scope / chaining of elements" do you have a link to explain this issue in more detail?
Do you have a release date for v5?

**Comment by christian-bromann** [comment]
> Do you have a release date for v5?

There is an alpha release out. No idea when we have the final release.

**Comment by cuongluu8** [comment]
I just tried out `5.0.0-alpha.11` and the above issue still exists in there too.
Doing a little more digging, this issue seems to be related to https://github.com/webdriverio/webdriverio/issues/2571.
