### ISSUE TITLE
BUG: webdriverio [v5] doesn't stop execution in case of exception is thrown in before() hook

### ISSUE THREAD

**Issue by erinev** [webdriverio/webdriverio#3887]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.7.15
 - **Mode:** standalone
 - **If WDIO Testrunner, running sync/async:** both [sync/async]
 - **Node.js version:** multiple [v8.9.0/v11.8.0]
 - **NPM version:** multiple [5.4.0/6.5.0]
 - **Browser name and version:** Chrome multiple versions [58/74]
 - **Platform name and version:** Multiple [WIN_8.1/WIN_10]
 - **Additional wdio packages used (if applicable):** "@wdio/cli": "5.7.15", "@wdio/devtools-service": "5.7.13", "@wdio/local-runner": "5.7.15", "@wdio/mocha-framework": "5.7.14", 
 "@wdio/spec-reporter": "5.7.13", "@wdio/sync": "5.7.13" 
([package.json](https://github.com/erinev/wdio-selenium-tests-playground/blob/master/package.json))

**Config of WebdriverIO**
[wdio.conf.js](https://github.com/erinev/wdio-selenium-tests-playground/blob/master/wdio.conf.js)

**Describe the bug**
If exceptions is thrown in before() hook test execution doesn't stop, but continues further in actual tests cases.

**To Reproduce**
100% simplified reproducible scenario is recreated in [repository](https://github.com/erinev/wdio-selenium-tests-playground) 

**Expected behavior**
If exception is thrown in before() hook execution of tests should be stopped. Now it is not stopped and if our login fails in before() hook all of our tests fails (because they can't be executed without login)

**Log**
![image](https://user-images.githubusercontent.com/4118417/56783434-696dde80-67f4-11e9-979c-7365efe9028c.png)

**Additional context**
I thought that maybe Sync mode creates this behavior so i tried to remove @wdio/sync package and make tests run asynchroniously but it did not resolved the issue - same behavior was experienced. Sync package is removed in [branch](https://github.com/erinev/wdio-selenium-tests-playground/tree/remove_wdio-sync_module)

**Comment by mgrybyk** [comment]
tests are not running for me if I have before block like this
```
    before: function (capabilities, specs) {
        throw new Error('oops')
    }
```

**Comment by mgrybyk** [comment]
The problem is that before block is executed before every test file, that's why you are seeing such behaviour

**Comment by mgrybyk** [comment]
if you move your code block to onPrepare block it would work as you expect, @erinev

**Comment by erinev** [comment]
@mgrybyk thanks for quick response. Unfortunaltely we can't use onPrepare() hook because it doesn't have `browser` context and we need to perform UI login before all tests.  
 
code:
```
onPrepare(config) {
    browser.url('https://google.com');
},
```

results in: `ReferenceError: browser is not defined`  

because before() hook is executed before each new spec file (not test case or describe, but spec file)
we workarrounded it this way: we have only one spec file all-test-cases.spec.js and inside it we require other files (== describes). So we have single login before all tests  

but we wan't to use proper beforeAll() hook which would have browser setuped (as before() has) in order to remove that hackish requiring other cases files into one.

**Comment by mgrybyk** [comment]
if this something that should be executed once you can follow approach mentioned here https://github.com/webdriverio/webdriverio/issues/3747

**Comment by erinev** [comment]
@mgrybyk if i understand correctly #3747 case is not the same like we have.   

In case you provided was needed to perform some kind of step BEFORE ALL TESTS == download files  
in our case we need to perform single time login (before all tests) because logging multiple times for each spec file would make tests run much longer and our company has maximum X logins per 1minute policy so if we wil have 10+ spec files we would breach that limit and we would need to code some kind of browser sleeps to not breach that login limit.  

so if i understood the issue you provided correctly this solution with some kind of extra hook step would not work for us, because we need to use same browser instance.

workflow looks like this:  

1) onPrepare hook (create failed screenshot folder)
2) before all step -> login to our website (browser.url('/login'); username.setValue, password.setValue, loginButton.click)
3) run each spec file (using same login session as created in step 2.)

i hope i explained clearly what we want to achieve, if not i can try to elaborate more on our case.

**Comment by erinev** [comment]
@mgrybyk we drifted from original problem a lot. Lets forget about single place where we could do the login. Problem is that before() hook doesn't stop execution on error.  

Do you agree that its a bug and should be fixed ? (because in my opinion execution should be stopped in case of exception is thrown)

**Comment by abjerstedt** [comment]
This is a known behavior and not exactly a bug. WDIO hooks run in a different fiber/process, and don't really report back to the main thread. 

I chatted with @christian-bromann about this several months ago, and I believe its actually intended.

Its hard to justify a hook crashing your entire run. You could be running 10 tests in parallel, but only one of them throws an error... why should that one test break all 10?

If you need to get mocha-bail to work, use mocha hooks ;) (those will terminate the test as expected).

**Comment by erinev** [comment]
@abjerstedt if you say that hooks doesn't report back to main thread which hooks do you have in mind exactly ? (just berfore() hook ?) because if i throw error in onPrepare() hook execution stops:  
```
onPrepare(config) {
    // On Prepare logic here (create folder for failed screenshots)

    throw Error('!!!!!!!!!!!!!!!!!!!! Some error is thrown in onPrepare() hook !!!!!!!!!!!!!!!!!!!!'); // TODO: why thrown exceptions (waitUntil, etc) doesn't stop execution ?
  },
```

could you elaborate more on hooks logic why some reports back to main thread and some not ?

**Comment by abjerstedt** [comment]
Hooks defined within the config are webdriverio hooks. 
Hooks defined within your spec files are mocha hooks.

If an exception is thrown within the webdriverio hook, the hook will terminate, but the test will continue.
If an exception is thrown within the mocha hook, the test will properly end.

@christian-bromann as I think about it, we still have a few hooks that I think should bubble up exceptions (like after/before command).

**Comment by erinev** [comment]
@abjerstedt here is a proof that wdio onPrepare() hook inside config stops test execution in case exception occurs. Separate [branch](https://github.com/erinev/wdio-selenium-tests-playground/blob/proof_that_onPrepare_hook_cancels_execution/wdio.conf.js#L41) is created to reproduce the issue. Result:  

![image](https://user-images.githubusercontent.com/4118417/56832822-a8904400-6875-11e9-944e-acc1a465f712.png)

**Comment by CrispusDH** [comment]
@erinev have you been thinking about using cookies? You can login once in script hook, take cookies/token whatever and in your tests using it. Also there's other ways to deal with your willingness without touching any hooks from wdio or mocha. If I will find a certain link I will post.

**Comment by abjerstedt** [comment]
onPrepare is kind of an exception, this hook gets called before the wdio process really starts.

**Comment by erinev** [comment]
@CrispusDH don't you think that it is a workarround ? if we have a framework why we need to workarround and perform login using API and setting cookies and so on. Login is not the only use case which would be convinient to have in a hook before each/all tests. 


@abjerstedt , @mgrybyk 
You guys just telling me how it is implemented now, but don't you feel at least small need as developers to think out of the box a bit ? i'm trying to challenge to think is current approach is best approach ? (maybe it could improved in some way ?)  

i wouldn't ask for some beforeAll tests hooks if other frameworks wouldn't have such implementation (for example: angulars protractor has onPrepare hook which has browser initialized and it runs before all tests not before each spec file and it handles exceptions properly.)  

could you provide example apart taking screenshot after failed test where hooks which doesn't handel exceptions might be utilized fully ? because any code might throw exception and if code execution continues then it means that it will have some side affect in the test it self if hook failed (because you do something in a hook to prepare for tests itself so if it is not prepared test will fail but not because Assert fails but because hook failed) 

i'm not a big guru in javascript and selenium testing and my opinion might be totally wrong ofcourse, but i'm interested in your opinion from another corner of view (not as it is now, but how it could be and if it should be like it is now, why ?).

**Comment by CrispusDH** [comment]
@erinev totally agree with you. That's why test for login should we one. Other tests should get already logged in user using cookie, token in URL, etc. because it would saving time.

**Comment by erinev** [comment]
Hi @christian-bromann,  

what do you think about current approach how wdio hooks are implemented ?  
**could it be made more useful by adding exception hadling & introducing beforeAll() hook ?**  
(woudn't it make sense ? maybe it is not easy to do, but i'm asking about possibility in the future to change **current, in my opinion limiting, approach** how hooks is imlemented now ?)

**Comment by christian-bromann** [comment]
The reason we don't handle errors in hooks is that I wanted to prevent problems and bugs of 3rd party services to ruin the experiences. Every time someone introduces such issue in a 3rd party service that we don't own it will cause people to raise issues here and even if we are able to fix them we won't be able to release the bug fix. I want to be more careful here to ensure that peoples tests run stable.

I don't recommend to put something that belongs in a test into a wdio hook. Something that is critical for your test should belong into the test not into the hook. If you need to log into somewhere to test things that login part should still be part of the test. There are ways to nicely encapsulate this into Page Objects.

I am happy to have a discussion around this. I might be wrong about this approach too.

**Comment by CrispusDH** [comment]
@erinev it would be nice if you will create demo repository with example what architecture do you have in tests and show you concerns.

**Comment by erinev** [comment]
@christian-bromann thanks for clarification why it is done this way. 

@CrispusDH ok i will prepare demo repo and i will add comments with reasoning for our approach and we can disscuss in that repo then.

**Comment by erinev** [comment]
for us it is not a big blocker that hooks doesn't handle exception because we use bail option so only one test will fail and it will be easy to detect it from screenshots that login failed. So im closing this issue. 

Let move disscusion to https://github.com/webdriverio/webdriverio/issues/3923, because for us single login is more important then error handling (we can live without it and its clear that you made it this way intentionally (from past experience)

i will create repo with our desired use case still. In issue above (#3923) i added additional context on single login use case.

**Comment by mgrybyk** [comment]
Guys, what if we introduce GlobalContext object shared across all the processes?

I think it should be useful and help deal with issues like this one.

**Comment by christian-bromann** [comment]
> I think it should be useful and help deal with issues like this one.

How?

**Comment by mgrybyk** [comment]
Ex, setting global flag to control flow.
It will allow to perform some action only once. Share some object across multiple spec files

**Comment by abjerstedt** [comment]
@mgrybyk whats the use case exactly?

**Comment by mgrybyk** [comment]
Isn't the problem that  before hook is actually executed for every spec file instead of executing once? Before is beforeSpec.

People are using it because it is the first hook where browser object is available. 

What are we missing is before hook with browser object available that executes only once.
To workaround this we may introduce some global object where it is possible to set some custom flag to identity if some action was executed or not.

if (!globalContext.doOnce) {
  ...
  globalContext.doOnce = true
}

**Comment by erinev** [comment]
@mgrybyk exactly what is missing for our use case.

**Comment by christian-bromann** [comment]
For this use case we have onPrepare/onComplete, no?

**Comment by mgrybyk** [comment]
Yes, but browser object is not available there.
Adding hook like beforeAll (or adding shared globalContext where we can set some flag and use it in before hook) in combination with ability to share browser session between spec files should help.

**Comment by christian-bromann** [comment]
If you want to have access to the browser object you need to start with the `before` hook but then if you want to run this in parallel you will get problems. How do you want to provide a hook that shares a browser session. WebdriverIO by design enforces new sessions for each spec file to make sure that tests are independent from each other.

**Comment by erinev** [comment]
our test files are independent from each other, but we have use case to run those tests in the same session (test real user full workflow). We will use workarround with single spec file for full workflow tests in single session.

Thanks for information how webdriver-io was designed.

**Comment by mgrybyk** [comment]
> How do you want to provide a hook that shares a browser session.

Spawn instance per session or limit instances to 1 in case shares instance approach is used

**Comment by abjerstedt** [comment]
> our test files are independent from each other, but we have use case to run those tests in the same session (test real user full workflow). We will use workarround with single spec file for full workflow tests in single session.
> 
> Thanks for information how webdriver-io was designed.

Just use abstraction. Take blocks of repeatable code and pull them out into importable functions. Mocha (and I believe Jasmine) both allow you import and invoke functions that call describe() or it() blocks. 
you could literally make a spec file import and invoke a section of code:

>import 'loginTest' from 'LoginTest'
>
>loginTest()

^---- you could then make all your spec files call this block of code

**Comment by erinev** [comment]
@abjerstedt how this is different then current before hook ? (we can easily achieve same functionality with before hook, if all spec files will include login test it is still be one login per file == same as before hook containing login functionality). or you had something different in mind ?
