### ISSUE TITLE
Incorrect doc: WebdriverIO Sync

### ISSUE THREAD

**Issue by mohanraj-r** [webdriverio/webdriverio#5597]
**Pre-check**
- [x] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**

I'd like to report
- [x] Unclear documentation
- [x] A typo
- [x] Missing documentation
- [x] Other

**Description of the improvement / report**
I am trying to test an async helper method I have created in sync mode to make sure users of the helper can use it in both sync and async mode using the following doc [Using WebdriverIO as standalone package](https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-sync/README.md#using-webdriverio-as-standalone-package) and noticed the following issues:

* `.then((browser) =>`
    - Typescript error: `TS2339: Property 'then' does not exist on type 'BrowserObject'`
    - Looking at `node_modules/webdriverio/webdriverio.d.ts` I see `remote()` returns a `BrowserObject` not a promise
    - If I suppress the error (assuming possible incorrect typedef) and run the test using wdio cli the `then` block does not run. 
       - e.g. `}).then((browser) => sync(() => { expect(true).toBe(false); })` still passes 
* Can you please add/improve doc to describe how to use a async helper method that uses `browser` object to work in `sync` mode. How can I design helper method or browser command that works in both sync and async mode?
   - If I try using my async helper method (e.g.`checkIssues()`) within the `sync()` block (without creating a `remote`, I get a `UnhandledPromiseRejectionWarning: Unhandled promise rejection.` 
       ```js
          sync(() => {
            browser.url(htmlFileWithIssues);
            expect(() => checkIssues()).toThrow();
           });
        ```
   - using `browser.call()` to wrap the async method as described in the doc doesn't help
     ```js 
      it('should work with sync mode', () => { 
        const sync = require('@wdio/sync').default;
        sync(() => {
            browser.url(htmlFileWithIssues);
            browser.call(async () => {
                expect(await checkIssues()).toThrow();
            });
        });
     ```
* `runner: true,` 
    - `runner` is a string, no longer a boolean, needs to be fixed e.g. to `runner: 'local'` (Fixed in https://github.com/webdriverio/webdriverio/pull/5598)
* [Switching Between Sync And Async](https://www.npmjs.com/package/@wdio/sync#switching-between-sync-and-async) has a typo: `you can still switch between both boths by using the` (Fixed in https://github.com/webdriverio/webdriverio/pull/5598)

**Comment by christian-bromann** [comment]
I am not quite sure if I understood all your questions here.

> * I see `remote()` returns a `BrowserObject` not a promise

That is indeed a bug.

> * how to use a async helper method that uses `browser` object to work in `sync` mode.

If you define a custom function like `checkIssues` you need to create your own custom type definitions for it I am not sure how WebdriverIO can help you here.

> * I get a `UnhandledPromiseRejectionWarning: Unhandled promise rejection.`

What is the error though?

> * (Fixed in #5598)

Thanks 👍

**Comment by christian-bromann** [comment]
> That is indeed a bug.

Fixed in #5599

**Comment by mohanraj-r** [comment]
Thanks @christian-bromann for the prompt response.
My primary question here is - How can I make a async helper method work in sync mode too ?
I have created a async helper method that uses the browser object to perform some checks on the loaded HTML page and returns the issues found. I will be publishing this as a library. But will it work for the users of the library who are using sync mode? I tried to test this using the `sync()` method explicitly - but couldn't get it to work. Hence wondering if this is supported? and if so what should I do to make the helper method work in both sync and async mode?

**Comment by christian-bromann** [comment]
@mohanraj-r not sure what project you are trying to build but the sync helper works as outlined [in the docs](https://www.npmjs.com/package/@wdio/sync#using-webdriverio-as-standalone-package). It should only be used if you use WebdriverIO in standalone mode.

I will close this issues as issues mentioned in your initial posting have been fixed. For further questions please join our [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge). Thanks!

**Comment by mohanraj-r** [comment]
Thanks for the clarification @christian-bromann 
* With the latest release (6.2.0) the `TS2339: Property 'then' does not exist on type 'BrowserObject'` is fixed.
* But still encountering `UnhandledPromiseRejectionWarning` while running my test in a separate file with `jest` in standalone mode:

```
(node:72018) UnhandledPromiseRejectionWarning: Error: Protocol error (Page.navigate): Target closed
.
(node:72018) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise whic
h was not handled with .catch(). To terminate the node process on unhandled promise rejection, use
the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:72018) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit
 code.

...

    at ../../node_modules/@wdio/logger/build/node.js:93:5

    console.error
      Unhandled error

      at process.uncaught (../../node_modules/jest-jasmine2/build/jasmine/Env.js:248:21)

    console.error
      net::ERR_ABORTED at file://wdio_test/packages/test-utils/__data__/a11yIssues.html
          at Frame.<anonymous> (wdio_test/node_modules/puppeteer-core/lib/helper.js:116:19)
          at Page.goto (wdio_test/node_modules/puppeteer-core/lib/Page.js:553:53)
          at Page.<anonymous> (wdio_test/node_modules/puppeteer-core/lib/helper.js:117:27)
          at DevToolsDriver.navigateTo (wdio_test/node_modules/devtools/build/commands/navigateTo.js:13:14)
          at Browser.wrappedCommand (wdio_test/node_modules/devtools/build/devtoolsdriver.js:92:47)
          at processTicksAndRejections (internal/process/task_queues.js:97:5)
          at wdio_test/packages/test-integration/__tests__/wdio.test.ts:35:21

      at process.uncaught (../../node_modules/jest-jasmine2/build/jasmine/Env.js:249:21)

    console.info
      2020-07-13T21:36:18.866Z INFO devtools: RESULT null

      at ../../node_modules/@wdio/logger/build/node.js:93:5
```

```js
const sync = require('@wdio/sync').default;

let browser: BrowserObject;

beforeAll(async () => {
    // Ref: https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-sync/README.md#using-webdriverio-as-standalone-package
    browser = await remote({
        runner: 'local',
        capabilities: {
            browserName: 'chrome',
        },
    });
});

afterAll(async () => {
    await browser.deleteSession();
});

it('should throw error in sync mode for html with issues', () => {
    expect(browser).toBeTruthy();
    sync(() => {
        browser.url(htmlFileWithA11yIssues);
        expect(() => checkIssues(browser)).toThrow();
    });
});
```

**Comment by christian-bromann** [comment]
You want to make sure to return the promise of the sync helper:

```js
it('should throw error in sync mode for html with issues', () => {
    expect(browser).toBeTruthy();
    return sync(() => {
        browser.url(htmlFileWithA11yIssues);
        expect(() => checkIssues(browser)).toThrow();
    });
});
```

**Comment by mohanraj-r** [comment]
Thanks @christian-bromann - of course I have to return the Promise 🤦 

But the test is still failing with `UnhandledPromiseRejectionWarning`. The only way I could get it to work was to wrap the call to the async `checkIssues()` in a `browser.call()`, i.e. 
from  :  
```js
expect(() => checkIssues(browser)).toThrow();
```
to       :   
```js
expect(() => {
   browser.call(async () => await checkIssues(browser));
}).toThrow();
```

which works but defeats the purpose of being able to use the async `checkIssues()` helper in sync mode without using `async`. Not sure if there is a way around this .. Tried using `browser.call()` within `checkIssues()` but that didn't help.
I am trying to avoid having to create 2 helpers to support the sync and async modes `checkIssuesSync()` and `checkIssuesAsync()` or the callers of the helper API having to deal with this using `browser.call()` etc.

**Comment by christian-bromann** [comment]
Ah, you didn't mention that `checkIssues` is also an async method, in this case there is no other way than using `browser.call` to make it sync.

> I am trying to avoid having to create 2 helpers to support the sync and async modes `checkIssuesSync()` and `checkIssuesAsync()` or the callers of the helper API having to deal with this using `browser.call()` etc.

Well there is no other way than doing it like this. You can't expect promises to magically disappear in the sync context ;-)

**Comment by mohanraj-r** [comment]
Thanks @christian-bromann 
Is there a way to detect if wdio is running in sync mode with `@wdio/sync` ?
How does `@wdio/sync` work automagically? 
[Sync mode vs async · WebdriverIO](https://webdriver.io/docs/sync-vs-async.html#how-to-enabledisable-sync-mode)
> To enable sync mode it's only required to install @wdio/sync package

How can I similarly make my async helper work seamlessly in both sync and async modes without the user having to know/care about it?

**Comment by christian-bromann** [comment]
> How can I similarly make my async helper work seamlessly in both sync and async modes without the user having to know/care about it?

You can just check if @wdio/sync is installed or not.
