### ISSUE TITLE
browser.executeAsync type checking on Typescript doesn't work.

### ISSUE THREAD

**Issue by DirkoOdendaal** [webdriverio/webdriverio#6206]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.10.5
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 14.13.1
 - **NPM version:** 6.14.8
 - **Browser name and version:**  Chrome 87
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** @wdio/spec-reporter, @wdio/selenium-standalone-service, @wdio/cli, @wdio/dot-reporter, @wdio/jasmine-framework, @wdio/junit-reporter, @wdio/firefox-profile-service, @wdio/local-runner, @wdio/sauce-service

**Config of WebdriverIO**
```js
{
  specs: ['spec/**/*.spec.ts'],
  specFileRetries: 1,
  connectionRetryCount: 2,
  bail: 0,
  maxInstances: 20,
  exclude: [],
  framework: 'jasmine',
  logLevel: 'error',
  runner: 'local',
  deprecationWarnings: false,
  outputDir,
  downloadDir,
  waitforTimeout: 4000,
  reporters: [
     // We use a custom reporter, which isn't relevant to the issue.
  ]
}
```

**Describe the bug**
We have a function to change a WireMock scenario in the beforeAll hook. We use the browser.executeAsync function to wrap a XMLHttpRequest.
This all works fine when using Plain JS, but when you want to use Typescript, the webdriverio typings does not include the normal callback in the function. 
Webdriverio documentation:
```js
browser.executeAsync(function(a, b, c, d, done) {
        // browser context - you may not access client or console
        setTimeout(() => {
            done(a + b + c + d)
        }, 3000);
    }, 1, 2, 3, 4).
```

From the typings file, webdriverio.d.ts, the callback is removed and this note added:
```ts
 // there is no way to add callback as last parameter after `...args`.
 // https://github.com/Microsoft/TypeScript/issues/1360
 // executeAsync: <T>(script: string | ((...arguments: any[], callback: (result: T) => void) => void), ...arguments: any[]) => Promise<T>;
```

When removing the callback, the script just hangs and returns a script timeout error.
```
[0-0] Error in ""before all" hook"
script timeout
(Session info: chrome=87.0.4280.66)
```

**To Reproduce**

Create a Typescript file that uses webdriverio type checking.

```js
 await browser.executeAsync(
    (_method, _body, _url, _contentType) => {
      const req = new XMLHttpRequest();
      req.open(_method, _url);
      req.setRequestHeader('Content-Type', _contentType);
      req.onload = () =>
        req.status === 200
          ? req.response
          : { xml_http_request_error: new Error(req.statusText) };
      req.onerror = e => {
       return  {
          xml_http_request_error: new Error(`Network Error: ${e}`),
        }
      });

      req.send(JSON.stringify(_body));
    },
    method,
    body,
    url,
    contentType
  );

```

**Expected behavior**
Expect the execution of browser.executeAsync to work the same way in PlainJS and Typescript.

**Log**
```
2020-12-07T12:32:20.907Z INFO webdriver: COMMAND executeAsyncScript(<fn>, <object>)
2020-12-07T12:32:20.907Z INFO webdriver: DATA {
  script: 'return (function (_method, _body, _url, _contentType) {\n' +
    '                        var req = new XMLHttpRequest();\n' +
    '                        req.open(_method, _url);\n' +
    "                        req.setRequestHeader('Content-Type', _contentType);\n" +
    '                        req.onload = function () {\n' +
    '                            return req.status === 200\n' +
    '                                ? req.response\n' +
    '                                : { xml_http_request_error: new Error(req.statusText) };\n' +
    '                        };\n' +
    '                        req.onerror = function (e) {\n' +
    '                            return ({\n' +
    '                                xml_http_request_error: new Error("Network Error: " + e),\n' +
    '                            });\n' +
    '                        };\n' +
    '                        req.send(JSON.stringify(_body));\n' +
    '                    }).apply(null, arguments)',
  args: [
    'PUT',
    { scenario: 'ZeZa_User3' },
    '/mocks/scenario',
    'application/json'
  ]
}
2020-12-07T12:32:50.961Z DEBUG webdriver: request failed due to response error: script timeout
2020-12-07T12:32:50.962Z WARN webdriver: Request failed with status 500 due to script timeout
  (Session info: chrome=87.0.4280.66)
```
**Additional context**

This is just the type checking that is the issue. If you ignore the type checking for this line, then all works as expected.
The below works where the typing is ignored:

```js
await browser.executeAsync(
    // @ts-ignore: explicit-function-return-type
    (_method, _body, _url, _contentType, done) => {
      const req = new XMLHttpRequest();
      req.open(_method, _url);
      req.setRequestHeader('Content-Type', _contentType);
      req.onload = () =>
        req.status === 200
          ? done(req.response)
          : done({ xml_http_request_error: new Error(req.statusText) });
      req.onerror = e =>
        done({
          xml_http_request_error: new Error(`Network Error: ${e}`),
        });

      req.send(JSON.stringify(_body));
    },
    method,
    body,
    url,
    contentType
  );
```

**Comment by christian-bromann** [comment]
@DirkoOdendaal thanks for filing the issue. As you already have pointed out this is a limitation in TypeScript. If you have any suggestions how to improve, please let us know.

**Comment by DirkoOdendaal** [comment]
@christian-bromann sure, I looked at Tuples with variable type arguments: https://github.com/microsoft/TypeScript/issues/1336

So maybe something like this could work:
`executeAsync: <T extends any[], U>(script: string | ((...arguments: [...T, (result: U) => void]) => void), ...arguments: T) => Promise<T>;`

I'll submit a PR for this and we can take it from there.

**Comment by christian-bromann** [comment]
@DirkoOdendaal do you think this patch can be supported in TS v3? If not @mgrybyk is it a reasonable move to require TS v4 with the next major update?

**Comment by mgrybyk** [comment]
We should drop ts 3 in next major version as far as all the internal types are build with ts 4.

Also, it would be nice to think how can we support multiple versions, at least minor. Many packages (jest for example) do that so it's not something new but requires some investigation.

**Comment by just-boris** [comment]
Hello!

Is there also a chance of reverting the `executeAsync` part of this commit: https://github.com/webdriverio/webdriverio/commit/ec87b10f627c51e9939466612519d0a52bfdd721

The current typings are practically unusable, because `callback` argument is required to make it work, but Typescript does not allow that.

**Comment by remss** [comment]
I agree with @just-boris, we should revert to previous typing because the current one triggers a TS error and there is no workaround yet.

**Comment by just-boris** [comment]
@christian-bromann I see you merged a big refactoring and types are fixed now: https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/commands/browser/executeAsync.ts

Since you are going to publish this as a new major version, will it be possible to lift the typescript requirement to 4.0 and bring the strict types?

**Comment by christian-bromann** [comment]
@just-boris we can do that. In fact proper typing the execute commands in v7 is still on the todo list. You wanna take a stab at it?

**Comment by christian-bromann** [comment]
@DirkoOdendaal would you like to take another look at our [current implementation](https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/commands/browser/executeAsync.ts#L73) and help us out with proper typings for it?

**Comment by Joozty** [comment]
Hi I think the typing is still wrong


when I use the example code I get these errors

```ts
   // Error cannot assign unknown to number
    const result: number = browser.executeAsync(function(a, b, c, d, done) {
        // browser context - you may not access client or console
        setTimeout(() => {
            // done is of type any
            done(a + b + c + d)
        }, 3000);
    }, 1, 2, 3, 4)
    
    // node.js context - client and console are available
    console.log(result) // outputs: 10
```


Sandbox here:
https://codesandbox.io/s/typescript-playground-export-forked-2c920?file=/index.ts:0-340

**Comment by fspinillo** [comment]
+1 to what @Joozty said

If you don't include a callback the function works just fine, but if you add in a callback then TypeScript will throw the error. Additionally, there is no Type error when using `execute`.
