### ISSUE TITLE
Cannot set property 'failures' of undefined > 6.10.5

### ISSUE THREAD

**Issue by Fr33z3m4n** [webdriverio/webdriverio#6237]
Environment (please complete the following information):

WebdriverIO version: 6.10.10
Mode: WDIO testrunner
If WDIO Testrunner, running sync/async: sync
Node.js version: 14.5.0
NPM version: 6.14.9
Browser name and version: multiple
Platform name and version: multiple
Additional wdio packages used (if applicable): 
"@rpii/wdio-html-reporter": "^6.3.1",
"@types/cucumber": "^6.0.1",
"@wdio/appium-service": "^6.10.10",
"@wdio/cli": "^6.10.10",
"@wdio/cucumber-framework": "^6.10.10",
"@wdio/local-runner": "^6.10.10",
"@wdio/sauce-service": "^6.10.10",
"@wdio/spec-reporter": "^6.10.6",
"@wdio/sync": "^6.10.10",
"appium": "^1.19.1",
"chromedriver": "^86.0.0",
 "cucumber": "^7.0.0-rc.0",
"typescript": "^4.1.3",
"wdio-chromedriver-service": "^6.0.4",
"webdriverio": "^6.10.10",
"yargs": "^16.2.0"

**Config of WebdriverIO**
An example of how you configured WebdriverIO config:
<pre>
logLevel: 'error',
specs: [ './src/features/**/*.feature' ],
 reporters: [ 'spec', [
            HtmlReporter,
            {
                debug: true,
                outputDir: './reports/html-reports/',
                filename: 'report.html',
                reportTitle: 'Ergebnisse',
                showInBrowser: false,
                useOnAfterCommandForScreenshot: false
            }
        ],
  framework: 'cucumber',
  cucumberOpts: {
    require: [ './src/steps/*.ts' ],
    strict: true,
    timeout: 600000
  },
  capabilities: [
    {
      autoWebview: true,
      autoWebviewTimeout: 60000,
      'sauce:options': [Object],
      'appium:chromeOptions': [Object],
      appiumVersion: '1.17.1',
      noReset: true,
      javascriptEnabled: true,
      locationContextEnabled: true,
      locationServicesAuthorized: true,
      locationServicesEnabled: true,
      handlesAlerts: true,
      nativeEvents: true,
      autoAcceptAlerts: true,
      networkConnectionEnabled: true,
      phoneOnly: true,
      deviceOrientation: 'portrait',
      app: 'storage:filename=<filename>',
      platformName: 'iOS',
      deviceName: undefined,
      platformVersion: '12',
      name: 'Platform: iOS # Version: 12 # Device: Random',
      privateDevicesOnly: [Function: privateDevicesOnly]
    }
  ],
  bail: 0,
  maxInstancesPerCapability: 3,
  user: '<username>',
  key: '<accesskey>',
  region: 'eu',
  services: [ 'sauce' ],
  connectionRetryTimeout: 360000,
  waitforTimeout: 1200000
}</pre>

Describe the bug
when i run the test sighting error message

<pre>[0-1] ERROR @wdio/local-runner: Failed launching test session: TypeError: Cannot set property 'failures' of undefined
    at HtmlReporter.<anonymous> (/<...>/node_modules/@rpii/wdio-html-reporter/node_modules/@wdio/reporter/build/index.js:153:32)
    at HtmlReporter.emit (events.js:315:20)
    at HtmlReporter.EventEmitter.emit (domain.js:486:12)
    at /<...>/node_modules/@wdio/runner/build/reporter.js:26:55
    at Array.forEach (<anonymous>)
    at BaseReporter.emit (/<...>/node_modules/@wdio/runner/build/reporter.js:26:24)
    at Runner._shutdown (/<...>/node_modules/@wdio/runner/build/index.js:165:23)
    at Runner.run (/<...>/node_modules/@wdio/runner/build/index.js:50:25)</pre>

**Comment by christian-bromann** [comment]
@Fr33z3m4n please update all your packages e.g. remove node_modules and package-lock and re-install all dependencies. This should fix the bug.

**Comment by mannysah** [comment]
I am having this problem. What should i check?

Versions of the packages that i am using are:
`    "@wdio/appium-service": "^6.11.0",
    "webdriverio": "^6.12.0",
    "@wdio/cli": "^6.12.0",
    "@wdio/jasmine-framework": "^6.11.0",
    "@wdio/local-runner": "^6.12.0",
    "@wdio/spec-reporter": "^6.11.0",
    "@wdio/sync": "^6.11.0",
    "@rpii/wdio-html-reporter": "^6.3.1",
`

**Comment by mannysah** [comment]
@christian-bromann any thoughts?
sorry about the formatting. Here are the versions:

    "@rpii/wdio-html-reporter": "^6.3.1",
    "@wdio/appium-service": "^6.11.0",
    "webdriverio": "^6.12.0",
    "@wdio/cli": "^6.12.0",
    "@wdio/jasmine-framework": "^6.11.0",
    "@wdio/local-runner": "^6.12.0",
    "@wdio/spec-reporter": "^6.11.0",
    "@wdio/sync": "^6.11.0",

**Comment by Fr33z3m4n** [comment]
@mannysah 
please update all your packages e.g. remove node_modules and package-lock and re-install all dependencies. 

This fixed my problem.

**Comment by mannysah** [comment]
@Fr33z3m4n I tried that, but that didn't resolve this error. Though this error is not causing any issues with functioning of the test suite, but when there are other errors it hides that error and shows only this error.

**Comment by mannysah** [comment]
This is my tree:

`npm ls webdriverio`

├─┬ @wdio/cli@6.12.0
│ └── webdriverio@6.12.0 
└─┬ @wdio/local-runner@6.12.0
  └─┬ @wdio/runner@6.12.0
    └── webdriverio@6.12.0  deduped

**Comment by mannysah** [comment]
Please note i get this error only when i use HtmlReporter `"@rpii/wdio-html-reporter": "^6.3.1"`. If i use only spec reporter this error doesn't happen.

**Comment by mannysah** [comment]
I overlooked the error location, my error is: 
`
[0-0] 2021-01-14T15:19:18.248Z ERROR @wdio/local-runner: Failed launching test session: TypeError: Cannot set property 'failures' of undefined at HtmlReporter.<anonymous> (<WORKSPACE>/node_modules/@wdio/reporter/build/index.js:153:32) at HtmlReporter.emit (events.js:315:20)
`

Error i am encountering is @ `/node_modules/@wdio/reporter/build/index.js` vs original error in this issue `/node_modules/@rpii/wdio-html-reporter/node_modules/@wdio/reporter/build/index.js:153:32`. 

They look to be the same issue though. Please let me know if i should create a different issue. 

On further research, the error comes from below section in the file `/node_modules/@wdio/reporter/build/index.js`. Looks like `runner:end` is being invoked while initializing HtmlReporter though `runner:start` has never been invoked and hence this.runnerStat is undefined. 

    this.on('runner:end', runner => {
      rootSuite.complete();
      this.runnerStat.failures = runner.failures;
      this.runnerStat.retries = runner.retries;
      this.runnerStat.complete();
      this.onRunnerEnd(this.runnerStat);
    });

**Comment by mannysah** [comment]
I might have found the root cause. One of my spec files had code which was all commented. because of which, below sequence of events happened: 

- Started worker for that spec file 
- Did NOT trigger `runner:start` event yet 
- Runner.run started but before triggering `runner:start` (Line 65 in file `/node_modules/@wdio/runner/build/index.js`), it determined there are no tests to run for this spec file and triggered a `runner:end` event at Line 49 in the same file.
- And hence the error 

Though this is not ideal, i think this can be easily fixed by moving Line 49 check after Line 65 where `runner:start` is triggered.

**Comment by nimeshbhatt** [comment]
@mannysah , is there any update on this issue? I am facing this error too.

**Comment by k-madhan** [comment]
I am also facing the same problem. Is there any solution ?

```
at Object.startWebDriverSession (/usr/lib/wdio/node_modules/webdriver/build/utils.js:34:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[0-4] 2021-03-04T15:55:16.878Z ERROR @wdio/local-runner: Failed launching test session: TypeError: Cannot set property 'failures' of undefined
    at AllureReporter.<anonymous> (/usr/lib/wdio/node_modules/@wdio/reporter/build/index.js:153:32)
    at AllureReporter.emit (events.js:314:20)
    at AllureReporter.EventEmitter.emit (domain.js:483:12)
    at /usr/lib/wdio/node_modules/@wdio/runner/build/reporter.js:26:56
    at Array.forEach (<anonymous>)
    at BaseReporter.emit (/usr/lib/wdio/node_modules/@wdio/runner/build/reporter.js:26:25)
    at Runner._shutdown (/usr/lib/wdio/node_modules/@wdio/runner/build/index.js:164:24)
    at Runner.run (/usr/lib/wdio/node_modules/@wdio/runner/build/index.js:54:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
2021-03-04T15:55:16.920Z DEBUG @wdio/local-runner: Runner 0-4 finished with exit code 1
```

**Comment by mannysah** [comment]
@k-madhan @nimeshbhatt if you have already tried other suggestions like updating all your packages and were not able to resolve this, i dont know if there is a solution. 

However, from what i experienced and found from my research is that this error was thrown (masking the actual error) when i used HtmlReporter and my test code had a runtime error (for ex: accessing property of an undefined object). For development work around i created a config without HtmlReporter and that helped me show the actual error. 

I added some notes for the actual reason for this to be happening above.

**Comment by k-madhan** [comment]
@mannysah Thanks. I will take a look at it.

**Comment by nimeshbhatt** [comment]
@mannysah thanks for the reply, 
I tried the same solution that is updating the packages and it worked. Though there were couple of more issues along the side which got highlighted when I started clearing my code. 

- I found a spec file which was completely commented - so, I removed it,
- I found the same error when I was trying to run all the spec file, though, I have mentioned "maxInstances" but the issue was I set the value of this attribute as 10 instead of 1 as I want to run my specs sequentially. 

So, first, I resolve the above 2 issues and than I updated all the packages and it worked.

**Comment by nklemiata** [comment]
Leaving a note here for others, who'll come up here in search for a fix :)

I started receiving this error in **smoke test runs** when added 3 more spec files to the project: 
`@wdio/local-runner[Failed launching test session: TypeError: Cannot set property 'failures' of undefined`
Each spec file has a single 'describe' suite in my case.
Versions updates did not help. 

Thanks to the hint from @[nimeshbhatt](https://github.com/nimeshbhatt), noticed 2 of the new specs **had no smoke tests** - so they had nothing to run in smoke runs. 

Simply marking at least 1 test in each of these suites as '_smoke' (based on my `--jasmineOpts.grep=_smoke` , your approach to filter smoke tests may be different) fixed the issue.

Why the wdio/local-runner fails to start a valid suite and skip all tests - is another question...
