### ISSUE TITLE
The client.on('error') triggers up the promise chain.

### ISSUE THREAD

**Issue by sean-hill** [webdriverio/webdriverio#629]
When `client.on('error')` is called I get multiple errors because it triggers up the promise chain.

**Comment by sean-hill** [comment]
Just curious when this bug fix would be released :smile: It's kinda affecting my process big time...

**Comment by christian-bromann** [comment]
not sure, I am on it

**Comment by sean-hill** [comment]
No worries, thanks @christian-bromann!

**Comment by christian-bromann** [comment]
This will be fixed with the next release. As you've seen I improved the error handling. I hope this will be fixed with my recent path.

**Comment by christian-bromann** [comment]
Fixed and published with `v3.2.0`

**Comment by sean-hill** [comment]
:+1: THANK YOU!!!

**Comment by sean-hill** [comment]
Hey @christian-bromann, not to be a downer or anything, but with the latest `3.2.0` release, `client.on('error')` does not fire if an element can not be found. The promise chain just stops.

**Comment by sean-hill** [comment]
Hey @christian-bromann I'm still having a little issue with the `client.on('error')` event. Some errors return `e.message` and `e.stack`. For instance the `NoSuchElement` error. Other others return `e.body.value.class` and `e.body.value.message` such as `org.openqa.selenium.NoAlertPresentException`. It'd be nice if there was some consistency with this. Currently I'm having to this:

	var error = e.message || e.body.value.class;
	var stack = e.stack || e.body.value.message;

Thanks!

**Comment by christian-bromann** [comment]
Agree! Created issue #747
