### ISSUE TITLE
 Couldn't initialise "@wdio/cucumber-framework". Error: Cannot find module '@cucumber/messages/dist/src/stream'

### ISSUE THREAD

**Issue by osmolyar** [webdriverio/webdriverio#6616]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/main/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.0.9
 - **Mode:** standalone
 - **If WDIO Testrunner, running sync/async:**sync
 - **Node.js version:**12.8
 - **NPM version:** 6.14.4
    "@wdio/allure-reporter": "^7.0.7",
    "@wdio/cli": "^7.0.9",
    "@wdio/cucumber-framework": "^7.0.7",
    "@wdio/dot-reporter": "^7.0.7",
    "@wdio/junit-reporter": "^7.0.7",
    "@wdio/local-runner": "^7.0.9",
    "@wdio/selenium-standalone-service": "^7.0.7",
    "@wdio/spec-reporter": "^7.0.7",
    "@wdio/sync": "^7.0.9",

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Describe the bug**
The following error occurs when launching wdio v7:

@wdio/local-runner: Failed launching test session: Error: Couldn't initialise "@wdio/cucumber-framework". Error: Cannot find module '@cucumber/messages/dist/src/stream'

**To Reproduce**

Launch wdio

**Expected behavior**
No error; tests run

**Log**

**Additional context**
Package.json is not changed from when it was working earlier today

> Please use the correct markdown

**Comment by christian-bromann** [comment]
This got fixed by the Cucumber team.

**Comment by Manjubhasini** [comment]
Hi Guys, We are using WDIO 6 with Mocha 
Getting the same issue. Only in CI not locally.
Have 95 specs in the wdio.config file.. After it executes 60 or so test cases we are the pipeline job gets stopped  with the following error..  Devops team tried wiping out all node modules before 'npm install' .. Still facing  the same problem

*\node_modules\@wdio\cli\build\interface.js:127
            throw new Error('Could not find job');
                  ^
Error: Could not find job
    at WDIOCLInterface.clearJob (*\node_modules\@wdio\cli\build\interface.js:127:19)
    at WDIOCLInterface.emit (events.js:315:20)
    at WDIOCLInterface.EventEmitter.emit (domain.js:467:12)
    at Launcher.endHandler (*\node_modules\@wdio\cli\build\launcher.js:222:28)
    at WorkerInstance.emit (events.js:315:20)
    at WorkerInstance.EventEmitter.emit (domain.js:467:12)
    at WorkerInstance._handleExit (*\node_modules\@wdio\local-runner\build\worker.js:93:14)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:467:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)

**Comment by christian-bromann** [comment]
@Manjubhasini I recommend to update to the latest WebdriverIO version to get rid of the issue.

**Comment by Manjubhasini** [comment]
Ok thanks. Will try that.
